const dayActivitiesSeed = [
  /* ItineraryID 5 */ {
    itineraryId: 4,
    Day01: "Arrival in Kathmandu",
    Day02: "Kathmandu sightseeing and Trip preperation.",
    Day03: "Trek from Phakding to Namche Bazaar.",
    Day04: "Trek from Phakding to Namche Bazaar.",
    Day05: "Acclimatization day at Namche Bazaar.",
    Day06: "Trek from Namche Bazaar to Tengboche",
    Day07: "Trek from Tengboche to Dingboche",
    Day08: "Acclimatization day at Dingboche",
    Day09: "Trek from Dingboche to Lobuche",
    Day10: "Trek from Lobuche - Gorakshep - Everest Base Camp - Gorakshep",
    Day11: "Trek from Gorakshep to Pheriche/Dingboche",
    Day12: "Trek from Pheriche/Dingboche to Namche Bazaar",
    Day13: "Trek from Namche Bazaar to Lukla",
    Day14: "Fly from Lukla to Kathmandu",
    Day15: "Final Departure",
    Day16: null,
    Day17: null,
    Day18: null,
    Day19: null,
    Day20: null,
  },
  /* ItineraryID 6 */ {
    itineraryId: 5,
    Day01: "Arrival in Kathmandu",
    Day02: "Kathmandu sightseeing and Trip preperation.",
    Day03: "Ride to Nayapul trek to Tikhedunga",
    Day04:
      "Trek from Tikhedunga to Ghorenpany. Pass by rhododendron and oak forests.",
    Day05: "Sunrise hike to Poon Hill then, trek to Tadapani.",
    Day06: "Trek from Tadapani to Chhomrong.",
    Day07: "Trek from Chhomrong to Dovan.",
    Day08: "Trek from Dovan to MBC",
    Day09: "Trek from MBC to Annapurna Base Camp and back to MBC.",
    Day10: "Trek from MBC to Jhinu.",
    Day11: "Trek from Jhinu to Nayapul drive to Pokhara.",
    Day12: "Pokhara sightseeing",
    Day13: "Drive from Pokhara to Kathmandu.",
    Day14: "Kathmandu sightseeing.",
    Day15: "Final Departure.",
    Day16: null,
    Day17: null,
    Day18: null,
    Day19: null,
    Day20: null,
  },
  /* ItineraryID 7 */ {
    itineraryId: 6,
    Day01: "Arrival in Kathmandu.",
    Day02: "Kathmandu sightseeing and Trip preperation.",
    Day03: "Fly from Kathmandy to Lukla. Trek to Phakding.",
    Day04: "Trek from Phakding to Namche Bazaar.",
    Day05: "Acclimatization day at Namche Bazaar.",
    Day06: "Trek from Namche to Tyangboche.",
    Day07: "Trek from Tyangboche to Pheriche.",
    Day08: "Trek from Pheriche to Lobuche.",
    Day09: "Acclimatization day at Lobuche.",
    Day10: "Trek from Lobuche to Gorakshep.",
    Day11: "Ascend Kalapatther and trek back to Lobuche.",
    Day12: "Trek from Lobuche to Chhukung.",
    Day13: "Trek from Chhukung to Island Peak Base Camp.",
    Day14: "Summit Day. Ascent Island Peak.",
    Day15: "Trek back to Chhukung.",
    Day16: "Trek from Chhukung to Pangboche.",
    Day17: "Trek from Pangboche to Namche Bazaar.",
    Day18: "Trek from Namche Bazaar to Lukla",
    Day19: "Fly from Lukla to Kathmandu",
    Day20: "Final Departure",
  },
];

module.exports = dayActivitiesSeed;
