// Seed Data
const productSeed = [
  {
    pName: "Everest Base Camp Trek",
    description:
      "Everest Base Camp Trek is a classic trip in the Everest region. The trek leads you to the heart of the Khumbu area, where you can feel the Sherpa hospitality and the Tibetan Buddhists culture. EBC trek became a popular trip after Tenzing Norgay and Edmund Hillary climbed Mount Everest with a trek through this trail in 1953. It has been turned into the tourist hub for the trekkers and high Himalayan climbers. If you love nature and want to be in the picturesque Himalayan zone, be ready to face the adventure of Everest base camp trekking. EBC trek embarks from the tiny airstrip of Lukla after a 35 min fly from Kathmandu. The Himalayan panoramas can be explored from the flight. The features of this trek are awesome landscape, dense alpine woods of rhododendron, birch, juniper and others. Some rare wild animals are found in the Sagarmatha National Park. Namche bazaar, Khumjung and Tengbuche are some of the spiritual places, where you can view the ancient Everest monasteries, Chhortens and Sherpa rituals. The beautiful natural scenery of the white peaks as Ama Dablam, Lhotse, Nuptse, Everest, Island Peak, Thamserku and the neighbouring peaks fascinates you. Namche and Dingbuche are suitable places to take a rest and acclimatization days. From Lobuche, the trek goes up to EBC and trek down to Gorakshep. Again, the charming day, you hike to Kalapatthar to view the golden sunrise. The trek retraces all the way down to Lukla and fly back to Kathmandu.",
    price: 1500,
  },
  {
    pName: "Annapurna Base Camp Trek",
    description:
      "Annapurna Base Camp Trek starts from the tourist town- Pokhara. You need to drive about an hour to the starting point. If you are time limited, take a walk through to the Ghandruk village and embark to the ABC. But we recommend the trek via Ghorepani and follow the trail to Chhomrong gradually to ABC. Mostly, the trek goes through the rhododendron forest and the breathtaking views of  the white peaks at the backdrop.The moderate ABC trek is also culturally a significant trek. Basically, Annapurna region is dominated by the ethnic groups as Gurung, Magar, Thakali, Brahmins, Chhetriyas and others. The ethnic groups are forward in the cultural preservation and unique social structure. They are also forward in offering the hospitality. As you pass their communities, you can feel about the hardship of the people in the Himalayan region and also get an opportunity to feel their cultural grandeur.The natural wonders are abundant. The Annapurna base camp is surrounded by the white peaks, so it is also known as the natural amphitheatre. During the trek to ABC, you can explore the panoramas of Fishtail, Annapurna I-IV, Lamjung Himal, Manaslu, Himchuli and dozens of peaks. Of course, the pine and rhododendron forest magnetize you with its perfect youth. If you want to take photographs, this trek is again one of the best trips.",
    price: 1800,
  },
  {
    pName: "Island Peak Climb",
    description:
      "The Island Peak (6189m) is also known as the Imja Tse, which is located in the Khumbu region of Nepal. It is marvellously positioned between the Ama Dablam and Lhotse Himalayas. The names from Imja Tse to Island Peak is given by the team of mountaineer led by Eric Shipton in 1952. It is exciting and challenging NMA authorized trekking peak. Mostly the mountaineers select this peak to climb before climbing the mountains more than 7000 meters. The interesting aspect of the Island Peak Climbing package is its combination with the Everest Base Camp Trekking. It is one of the most dreamed trekking routes for the trekkers from all over the world. Everest region or the Khumbu region is populated by the Sherpa groups, who are forward in the climbing activities. It is said that without Sherpa, no climbing trip becomes successful. Lukla is a gateway of this region. The climbing team heads through Phakding, Namche Bazaar to all the way to the Everest Base Camp and Kalapatthar and trek down to the Chhukung. The real climbing trip starts from here. With the help of different equipments like crampons on boots, ice axe, harness, using climbing ropes, Carabineers, you can reach the summit of the Island Peak. The views of the Everest region mountains are stunning. You can explore Mt. Everest, Lhotse, Nuptse, Ama Dablam, Thamserku and other snow covered mountains. During the trip, you can explore the geographical panoramas and the Sherpa cultural practices.",
    price: 2200,
  },
];

module.exports = productSeed;
